name: Go package

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      -
      # action文档：
      # https://github.com/marketplace/actions/setup-sqlite-environment
      - uses: actions/setup-sqlite@v1
        with:
          sqlite-version: 3.40.0
          sqlite-year: 2023

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Test
        run: go test -v ./...
        env:
          STORAGE_LOCK_SQLITE3_DB_PATH: "storage_lock_test.db3"